# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 17:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('smart', models.BooleanField()),
                ('fan_speed', models.CharField(choices=[('O', 'Off'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='O', max_length=1)),
                ('brightness', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
