# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='light',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fan',
            name='fan_speed',
            field=models.CharField(choices=[('O', 'off'), ('L', 'low'), ('M', 'medium'), ('H', 'high')], default='O', max_length=1),
        ),
    ]
