# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0002_auto_20171104_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_speed', models.CharField(choices=[('O', 'off'), ('L', 'low'), ('M', 'medium'), ('H', 'high')], default='O', max_length=1)),
                ('brightness', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('light', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='fan',
            name='brightness',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='fan_speed',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='light',
        ),
        migrations.AddField(
            model_name='fanstate',
            name='fan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='fan.Fan'),
        ),
    ]
